apiVersion: v1
kind: Service
metadata:
  name: graphite
spec:
  selector:
    app: graphite
  ports:
    - name: metrics
      protocol: TCP
      port: 8125
      targetPort: 8125
    - name: web-ui
      protocol: TCP
      port: 80
      targetPort: 80